version: '3'

services:
    postgres:
        container_name: 'cat-management-postgres'
        build:
            context: ./.docker/postgres
            dockerfile: Dockerfile
        restart: always
        shm_size: 4g
        ports:
            - 5446:5432
        volumes:
            - "./.docker/postgres/data:/var/lib/postgresql/data:rw"
        environment:
            - POSTGRES_DB=cat_management
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - PGDATA=/var/lib/postgresql/data
            - POSTGRES_HOST_AUTH_METHOD=trust

    php:
        build: .docker/php
        container_name: 'cat-management-php'
        volumes:
            - ./back-end/.:/var/www/html/cat-management
        links:
            - postgres
        depends_on:
            - php-build

    php-build:
        image: php
        build: .docker/php
        container_name: 'cat-management-php-build'
        depends_on:
            - node
        volumes:
            - ./back-end/.:/var/www/html/cat-management
        links:
            - postgres
        command: >
            bash -c "cd /var/www/html/cat-management && composer setup"

    nginx:
        build:
            context: .docker
            dockerfile: nginx/Dockerfile
        container_name: 'cat-management-nginx'
        ports:
            - 8020:80
        depends_on:
            - php
        volumes:
            - ./back-end/.:/var/www/html/cat-management

    node:
        container_name: 'cat-management-node'
        build: .docker/node
        volumes:
            - './front-end/.:/home/node/app'
        ports:
            - '801:8080'
        command: >
            bash -c "yarn install && yarn serve"

volumes:
    postgres:
        driver: local
    php:
        driver: local
